// vant-ui组件库的按需引入
import Vue from 'vue'
import { Tabbar, TabbarItem, NavBar, Toast, Search, Swipe, SwipeItem, Grid, GridItem, NoticeBar, Icon, Lazyload, Rate, ActionSheet, GoodsAction, GoodsActionIcon, GoodsActionButton, Dialog, SubmitBar, Checkbox, CheckboxGroup, Button, Empty, ContactCard, Card, CouponCell, CouponList, Popup, AddressList, AddressEdit, Area, Tab, Tabs } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Area)
Vue.use(AddressEdit)
Vue.use(AddressList)
Vue.use(Popup)
Vue.use(CouponCell)
Vue.use(CouponList)
Vue.use(Card)
Vue.use(ContactCard)
Vue.use(Empty)
Vue.use(Button)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(SubmitBar)
Vue.use(Dialog)
Vue.use(GoodsAction)
Vue.use(GoodsActionButton)
Vue.use(GoodsActionIcon)
Vue.use(ActionSheet)
Vue.use(Rate)
Vue.use(Lazyload)
Vue.use(Icon)
Vue.use(NoticeBar)
Vue.use(GridItem)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Grid)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
